---
# yamllint disable rule:line-length

- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Verify | paperless.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | paperless.conf'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/paperless.conf"
          }}'
        test_file: '/opt/paperless/paperless/paperless.conf'
        test_owner: 'paperless'
        test_group: 'paperless'
        test_mode: '0640'
        test_diff: true

    # Paperless will fail if configuration is bad (r_pufky.deb.systemd)
    - name: 'Verify | assert Paperless-NGX services active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"paperless-consumer.service" in ansible_facts.services'
          - 'ansible_facts["services"]["paperless-consumer.service"]["state"] == "running"'
          - '"paperless-scheduler.service" in ansible_facts.services'
          - 'ansible_facts["services"]["paperless-scheduler.service"]["state"] == "running"'
          - '"paperless-task-queue.service" in ansible_facts.services'
          - 'ansible_facts["services"]["paperless-task-queue.service"]["state"] == "running"'
          - '"paperless-webserver.service" in ansible_facts.services'
          - 'ansible_facts["services"]["paperless-webserver.service"]["state"] == "running"'
          - '"redis-server.service" in ansible_facts.services'
          - 'ansible_facts["services"]["redis-server.service"]["state"] == "running"'
        fail_msg: |
          ✘ Paperless-NGX services should be enabled and running:

            paperless-consumer.service: {{ ansible_facts["services"]["paperless-consumer.service"]["state"] }}
           paperless-scheduler.service: {{ ansible_facts["services"]["paperless-scheduler.service"]["state"] }}
          paperless-task-queue.service: {{ ansible_facts["services"]["paperless-task-queue.service"]["state"] }}
           paperless-webserver.service: {{ ansible_facts["services"]["paperless-webserver.service"]["state"] }}
                  redis-server.service: {{ ansible_facts["services"]["redis-server.service"]["state"] }}

    - name: 'Verify | /opt/paperless/paperless/data'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /opt/paperless/paperless/data'
        test_file: '/opt/paperless/paperless/data'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true

    - name: 'Verify | /data/data/db.sqlite3'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /data/data/db.sqlite3'
        test_file: '/data/data/db.sqlite3'
        test_owner: 'paperless'
        test_group: 'paperless'
        test_mode: '0644'
        test_state: 'file'
        test_diff: true

    - name: 'Verify | /etc/ImageMagick-6/policy.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/ImageMagick-6/policy.xml'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/policy.xml"
          }}'
        test_file: '/etc/ImageMagick-6/policy.xml'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: 'Verify | /usr/local/bin/jbig2'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /usr/local/bin/jbig2'
        test_file: '/usr/local/bin/jbig2'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true

    - name: 'Verify | /usr/local/bin/gs'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /usr/local/bin/gs'
        test_file: '/usr/local/bin/gs'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true
