---
###############################################################################
# Paperless NGX jbig2enc Compression Library.
###############################################################################
# Build and install jbig2enc high compressions library for pdfs.
#
# This avoids the need to trust a privately maintained russian repository:
# https://notesalexp.org/.
#
# Args:
#   _pngx_ocr_packages: list of str containing OCR packages to install.
#   _pngx_jbig2enc_dir: str jbig2enc build location.
#   _pngx_jbig2enc_version: str jbig2enc release.
#
# Reference:
# * https://github.com/paperless-ngx/ansible
# * https://github.com/agl/jbig2enc

- name: 'jbig2enc | create build directory'
  ansible.builtin.tempfile:
    path:  '{{ pngx_default_jbig2enc_dir }}'
    state: 'directory'
  register: _pngx_jbig2enc_build

- name: 'jbig2enc | download jbig2enc {{ pngx_jbig2enc_version }}'
  ansible.builtin.git:
    repo:      '{{ pngx_default_jbig2enc_repo }}'
    dest:      '{{ _pngx_jbig2enc_build.path }}'
    version:   '{{ pngx_jbig2enc_version }}'
    recursive: true

# The 0.29 release sets the minor release version as 0.28. Patch 0.29 release
# to build with the correct version so builds are not re-triggered every run.
# This repository is essentially abandoned so it will likely never be fixed.
- name: 'jbig2enc | apply patch to correctly report version 0.29'
  ansible.posix.patch:
    basedir: '{{ _pngx_jbig2enc_build.path }}'
    src:     'jbig2enc-0.29-fix-reported-version.patch'
    strip:   1
    state:   'present'
  when: _pngx_jbig2enc_version == '0.29'

- name: 'jbig2enc | generating build files' # noqa no-changed-when wrapped make command no change exit codes.
  ansible.builtin.command: './autogen.sh'
  args:
    chdir: '{{ _pngx_jbig2enc_build.path }}'

- name: 'jbig2enc | configure' # noqa no-changed-when wrapped make command no change exit codes.
  ansible.builtin.command: './configure'
  args:
    chdir: '{{ _pngx_jbig2enc_build.path }}'

- name: 'jbig2enc | install'
  community.general.make:
    chdir:  '{{ _pngx_jbig2enc_build.path }}'
    target: 'install'
  become: true

- name: 'jbig2enc | cleanup build directory'
  ansible.builtin.file:
    path:  '{{ _pngx_jbig2enc_build.path }}'
    state: 'absent'
