---
###############################################################################
# Manager Paperless NGX Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   pngx_user: string paperless username.
#   pngx_group: string paperless group.
#   pngx_create_user: boolean true to create role default user.
#   pngx_default_user: dict containing builitin.user options for paperless.
#   pngx_default_group: dict containing builitin.group options for paperless.

- name: 'manage users | confirm user exists'
  ansible.builtin.command: 'id {{ pngx_user }}'
  register: _pngx_user_exists
  changed_when: _pngx_user_exists.rc > 0
  failed_when: false

- name: 'manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ pngx_group }}'
  register: _pngx_group_exists
  changed_when: _pngx_group_exists.rc > 0
  failed_when: false

- name: 'manage users | create paperless group'
  ansible.builtin.group:
    name:  '{{ pngx_default_group.name }}'
    gid:   '{{ pngx_default_group.gid }}'
    state: 'present'
  when: pngx_create_user and _pngx_group_exists.rc != 0

- name: 'manage users | create paperless user (logins disabled)'
  ansible.builtin.user:
    name:            '{{ pngx_default_user.name }}'
    group:           '{{ pngx_default_user.group }}'
    uid:             '{{ pngx_default_user.uid }}'
    shell:           '{{ pngx_default_user.shell }}'
    home:            '{{ pngx_default_user.home }}'
    comment:         '{{ pngx_default_user.comment }}'
    create_home:     '{{ pngx_default_user.create_home }}'
    password:        '{{ pngx_default_user.password }}'
    password_lock:   '{{ pngx_default_user.password_lock }}'
    update_password: '{{ pngx_default_user.update_password }}'
    expires:         '{{ pngx_default_user.expires }}'
    system:          '{{ pngx_default_user.system }}'
    state:           'present'
  when: pngx_create_user and _pngx_user_exists.rc != 0
