---
###############################################################################
# Paperless NGX NLTK (Natural Language Toolkit).
###############################################################################
# Machine learning langauge processor. Install NLTK with Snowball Stemmer,
# Stopwords, and Punkt.
#
# Reference:
# * https://docs.paperless-ngx.com/setup/#bare_metal
# * https://www.nltk.org/install.html
# * https://www.nltk.org/data.html

- name: 'nltk | nltk data download (may take a while)'
  ansible.builtin.debug:
    msg: |
      Downloading additional 20.6MB data for NLTK. This may take a few minutes.

- name: 'nltk | nltk data download ~20.6MB'
  ansible.builtin.command: '{{ _pngx_venv }}/bin/python3 -W ignore::RuntimeWarning -m nltk.downloader -d {{ pngx_nltk_dir }} {{ item }}'
  register: _pngx_nltk_data_download
  changed_when: '"already up-to-date" not in _pngx_nltk_data_download.stderr'
  become: true
  become_user: '{{ pngx_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  loop: '{{ pngx_default_nltk_data }}'