---
###############################################################################
# Validate
###############################################################################
# Start Paperless-NGX services and confirm they are active and running.

- name: 'Validate | start services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'started'
  failed_when: false
  loop: '{{
      ["redis-server.service" if _paperless_ngx_srv_redis_enable.raw else "",
       "paperless-consumer.service",
       "paperless-scheduler.service",
       "paperless-task-queue.service",
       "paperless-webserver.service",
       "paperless-cache.service",
       "paperless-cache.timer"] | select()
    }}'

- name: 'Validate | query service status'
  ansible.builtin.service_facts:

- name: 'Validate | query paperless-cache.timer status'
  ansible.builtin.command: 'systemctl status paperless-cache.timer'
  register: _paperless_ngx_timers
  changed_when: false

- name: 'Validate | assert services running'
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].state == 'running'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                     Service failed to start.                      │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ {{ item }}
  loop:
    - 'paperless-consumer.service'
    - 'paperless-scheduler.service'
    - 'paperless-task-queue.service'
    - 'paperless-webserver.service'

- name: 'Validate | assert timer services enabled'
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].status == 'enabled'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                    Service should be enabled.                     │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ {{ item }}
  loop:
    - 'paperless-cache.service'

- name: 'Validate | assert paperless-cache.timer active'
  ansible.builtin.assert:
    quiet: true
    that:
      - _paperless_ngx_timers.rc == 0
      - '"Active: active" in _paperless_ngx_timers.stdout'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │             paperless-cache.timer should be enabled.              │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯
