---
###############################################################################
# User Data
###############################################################################
# Default test with user data management enabled.
#
# Tests:
# * paperless_ngx_srv_user_data_manage_enable=true.
# * paperless.conf set.
# * Paperless-NGX services are active and running.
# * Granian overrides are set correctly.
# * ImageMaick has PDF processing enabled.
# * install directory locations are removed.
# * sqlite database exists in data directory.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        paperless_ngx_srv_user_data_manage_enable: true
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'paperless'
            version: 'v2.16.2'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/paperless-ngx-v2.16.2.tar.xz"
              }}'
          - comment: 'JBIG2enc'
            version: '0.30'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/0.30.tar.gz"
              }}'
          - comment: 'Ghostscript'
            version: 'gs10051'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/ghostpdl-10.05.1.tar.xz"
              }}'
        paperless_ngx_srv_nltk_data: []
        paperless_ngx_cfg_dbengine: 'sqlite'
        paperless_ngx_cfg_secret_key: 'test'
platforms:
  - name: 'paperless_ngx-debian-12-user_data'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '8000/tcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
