---
###############################################################################
# Paperless NGX Handlers
###############################################################################

- name: 'Handlers | reload redis memcache'
  listen: 'Handlers | reload paperless_ngx'
  when: paperless_ngx_service_redis_enable
  ansible.builtin.systemd:
    name: 'redis-server'
    enabled: true
    state: 'restarted'

- name: 'Handlers | reload paperless-consumer'
  listen: 'Handlers | reload paperless_ngx'
  ansible.builtin.systemd:
    name: 'paperless-consumer'
    enabled: true
    state: 'restarted'

- name: 'Handlers | reload paperless-scheduler'
  listen: 'Handlers | reload paperless_ngx'
  ansible.builtin.systemd:
    name: 'paperless-scheduler'
    enabled: true
    state: 'restarted'

- name: 'Handlers | reload paperless-task-queue'
  listen: 'Handlers | reload paperless_ngx'
  ansible.builtin.systemd:
    name: 'paperless-task-queue'
    enabled: true
    state: 'restarted'

- name: 'Handlers | reload paperless-webserver'
  listen: 'Handlers | reload paperless_ngx'
  ansible.builtin.systemd:
    name: 'paperless-webserver'
    enabled: true
    state: 'restarted'
