---
###############################################################################
# Default Paperless-NGX Package Dependencies
###############################################################################
# Default required packages for Paperless-NGX install.
#
# Updates:
# * Branch for new Debian releases.
# * You will not remember all changes. Keep a separate change log.
# * Use bare-metal docs to validate package/process changes.
# * Update role defaults (includes updating vars, defaults, tasks):
# * Update tests for any changes.
# * Standard role validation testing (yamllint, ansible-lint, to-do, no-qa).
#
# Reference:
# * https://docs.paperless-ngx.com/setup/#bare_metal
# * https://github.com/paperless-ngx/paperless-ngx/blob/dev/Dockerfile

paperless_ngx___release: "{{ {} | r_pufky.data.v3(

    _date='2026-02-27',
    _debian='trixie',
    _app='v2.20.8',
    _jb2e='0.30',
    _gs='10.06.0',
  ) }}"

###############################################################################
# APT Packages
###############################################################################

paperless_ngx___packages:
  # Standard Paperless-NGX packages.
  - 'python3'
  - 'python3-pip'
  - 'python3-dev'
  - 'default-libmysqlclient-dev'
  - 'pkg-config'
  - 'fonts-liberation'
  - 'imagemagick'
  - 'gnupg2'  # Use full GPG suite instead of bare bones gnupg.
  - 'libpq-dev'
  - 'libmagic-dev'
  - 'mariadb-client'
  - 'libzbar0'
  - 'poppler-utils'
  - 'python3-zxing-cpp'  # ZXING paperless_ngx_cfg_consumer_barcode_scanner.

  # OCRmyPDF.
  - 'unpaper'
  # - 'ghostscript'  # See security warning; use a custom build.
  - 'icc-profiles-free'
  - 'qpdf'
  - 'libleptonica6'  # Package name changed from liblept5.
  - 'libxml2'
  - 'pngquant'
  - 'zlib1g'
  - 'tesseract-ocr'  # tesseract-ocr-{LANG} packages automatically installed.

  # Python3 dependencies (Explicit. Auto-included with other packages).
  - 'build-essential'
  - 'python3-setuptools'
  - 'python3-wheel'

  # SQLite support.
  - 'sqlite3'

  # JBIG2enc build support.
  - 'autotools-dev'
  - 'automake'
  - 'libtool'
  - 'libleptonica-dev'
  - 'zlib1g-dev'

  # Custom packages for CLI PDF handling.
  - 'img2pdf'  # Provide lossless image import to PDF via CLI.
  - 'optipng'  # Lossless PNG compression.

  # Ansible.
  - 'ca-certificates'  # SSL support for ansible.builtin.get_url.
  - 'xz-utils'  # xz archives.
  - 'tox-uv'  # python3 uv support.
  - 'curl'

paperless_ngx___redis:  # includes redis-server, redis-tools.
  - 'redis'

###############################################################################
# Paperless-NGX
###############################################################################
# User defined version is overlayed in prep.yml.
#
# Reference:
# * https://github.com/paperless-ngx/paperless-ngx/releases

paperless_ngx___repo_url:
  'https://github.com/paperless-ngx/paperless-ngx/releases/download/'
paperless_ngx___package:
  '{{ "paperless-ngx-" ~ paperless_ngx___release._app ~ ".tar.xz" }}'

paperless_ngx___app: "{{ {} | r_pufky.data.v3(

    _version=paperless_ngx___release._app,
    _package=paperless_ngx___package,
    _etc_dir='/etc/opt/paperless',
    _cfg='/etc/opt/paperless/paperless.conf',
    _var_dir='/var/opt/paperless',
    _opt_dir='/opt/paperless',
    _src_dir='/opt/paperless/src',
    _live_dir='/opt/paperless/src/' ~ paperless_ngx___release._app,
    _work_dir='/opt/paperless/src/' ~ paperless_ngx___release._app ~ '/src',
    _venv_dir='/opt/paperless/src/' ~ paperless_ngx___release._app ~ '/.venv',
    _base_url=paperless_ngx___repo_url,
    _url=(
      paperless_ngx___repo_url ~ paperless_ngx___release._app ~ '/' ~
      paperless_ngx___package
    ),
  ) }}"

###############################################################################
# JBIG2 Encoder Support
###############################################################################
# Lossless high-compression used in pdf/a formats. Debian provided package is
# 0.19; Paperless requires 0.29+.
#
# Reference:
# * https://github.com/agl/jbig2enc/releases

paperless_ngx___jb2e_repo_url:
  'https://github.com/agl/jbig2enc/archive/refs/tags/'
paperless_ngx___jb2e_package: '{{ paperless_ngx___release._jb2e ~ ".tar.gz" }}'

paperless_ngx___jb2e: "{{ {} | r_pufky.data.v3(

    _version=paperless_ngx___release._jb2e,
    _package=paperless_ngx___jb2e_package,
    _opt_dir='/opt/jbig2enc',
    _src_dir='/opt/jbig2enc/src',
    _live_dir='/opt/jbig2enc/src/' ~ paperless_ngx___release._jb2e,
    _url=paperless_ngx___jb2e_repo_url ~ paperless_ngx___jb2e_package,
  ) }}"

###############################################################################
# Ghostscript Support
###############################################################################
# Ghostscript release tags and versions do not match; there is not enough
# information in the release tag to parse version from the tag. Use the release
# version from the download link and parse the tags in prep.
#
# Security: CVE-2023-43115
#   CVE:
#   * https://nvd.nist.gov/vuln/detail/cve-2023-43115
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27835
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27832
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27831
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27836
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27830
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27833
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27837
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27834
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46951
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46952
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46953
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46954
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46955
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46956
#   * https://nvd.nist.gov/vuln/detail/cve-2024-33869
#   * https://nvd.nist.gov/vuln/detail/cve-2023-52722
#   * https://nvd.nist.gov/vuln/detail/cve-2024-33870
#   * https://nvd.nist.gov/vuln/detail/cve-2024-33871
#   * https://nvd.nist.gov/vuln/detail/cve-2024-29510
#
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27835
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27832
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27831
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27836
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27830
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27833
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27837
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-27834
#   * https://nvd.nist.gov/vuln/detail/CVE-2025-46646
#  Decision: do not use package - multiple vulnerabilities with PDF corruption
#      for existing files, packages (and backports) affected.
#  Mitigation: use source release. Default gs binary to custom binary
#      /usr/local/bin/gs instead of /usr/bin/gs.
#  Reference:
#  * https://github.com/tteck/Proxmox/discussions/3265
#  * https://github.com/ArtifexSoftware/ghostpdl-downloads/releases

paperless_ngx___gs_repo_url:
  'https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/'
paperless_ngx___gs_package:
  '{{ "ghostpdl-" ~ paperless_ngx___release._gs ~ ".tar.xz" }}'
paperless_ngx___gs_release: "{{
    'gs' ~ paperless_ngx___release._gs | replace('.', '') | replace('-', '')
  }}"

paperless_ngx___gs: "{{ {} | r_pufky.data.v3(

    _version=paperless_ngx___release._gs,
    _package=paperless_ngx___gs_package,
    _opt_dir='/opt/ghostscript',
    _src_dir='/opt/ghostscript/src',
    _live_dir='/opt/ghostscript/src/' ~ paperless_ngx___release._gs,
    _url=(
      paperless_ngx___gs_repo_url ~ paperless_ngx___gs_release ~ '/' ~
      paperless_ngx___gs_package
    ),
  ) }}"

###############################################################################
# NLTK Support
###############################################################################
# Machine learning language processor. Store in /opt as it is a third-party
# install.
#
# Reference:
# * https://www.nltk.org/nltk_data/
# * https://www.nltk.org/data.html
# * https://www.nltk.org/install.html

paperless_ngx___nltk: "{{ {} | r_pufky.data.v3(

    _opt_dir='/usr/share/nltk_data',
    _packages=('nltk', 'numpy'))
  }}"

###############################################################################
# Default Paperless-NGX User/Group
###############################################################################

paperless_ngx___group:
  name: 'paperless'
  gid: 950

paperless_ngx___user:
  name: 'paperless'
  group: 'paperless'
  uid: 950
  shell: '/usr/sbin/nologin'
  home: '/var/opt/paperless'
  comment: 'paperless system account,,,'
  create_home: true
  password: '!'
  password_lock: true
  update_password: 'always'
  expires: -1
  system: true
