---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Converge | role | r_pufky.media.paperless_ngx'
      ansible.builtin.include_role:
        name: 'r_pufky.media.paperless_ngx'

    - name: '{{ "Converge | test | minimal " ~ paperless_ngx___app._cfg }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'template.yml'
      vars:
        test_name:
          '{{ "Converge | test | minimal " ~ paperless_ngx___app._cfg }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/paperless.conf.role_defaults"
          }}'
        test_file: '{{ paperless_ngx___app._cfg }}'
        test_owner: 'paperless'
        test_group: 'paperless'
        test_mode: '0640'
        test_diff: true
        test_content: |
          # Minimal configuration for Paperless-NGX.
          #
          # Precedence: config > environment.
          #
          # Have a look at the docs for documentation.
          # https://docs.paperless-ngx.com/configuration/

          PAPERLESS_SECRET_KEY=NjA0NTRmZDE4MzkxZWY0NjkyYmFkNjdkNDIwZDFlNGVjMmExZDg3ODc4YTJiOGIz
          PAPERLESS_CONVERT_TMPDIR=/tmp
          PAPERLESS_CONSUMPTION_DIR=/var/opt/paperless/consume
          PAPERLESS_DATA_DIR=/var/opt/paperless/data
          PAPERLESS_EMPTY_TRASH_DIR=/var/opt/paperless/trash
          PAPERLESS_MEDIA_ROOT=/var/opt/paperless/media
          PAPERLESS_GS_BINARY=/usr/local/bin/gs
          PAPERLESS_ADMIN_USER=admin
          PAPERLESS_ADMIN_MAIL=root@localhost
          PAPERLESS_ADMIN_PASSWORD=admin

    # Re-run with user test paperless.conf.
    - name: 'Converge | role | r_pufky.media.paperless_ngx'
      ansible.builtin.include_role:
        name: 'r_pufky.media.paperless_ngx'
      vars:
        paperless_ngx_cfg_file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/paperless.conf"
          }}'
        paperless_ngx_flg_backup: false
        paperless_ngx_flg_maintenance: false
        paperless_ngx_flg_install: false
        paperless_ngx_flg_config: true
        paperless_ngx_flg_migrate: false
        paperless_ngx_flg_start: true
