---
###############################################################################
# Default ()
###############################################################################
# Default configuration is deployed successfully.
#
# Tests:
# * Minimal paperless.conf set (tested in converge).
# * User provided paperless.conf set.
# * Paperless-NGX services are active and running.
# * Granian overrides are set correctly.
# * ImageMaick has PDF processing enabled.
# * sqlite database exists in data directory.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        url_inject_enable: true
platforms:
  - name: 'paperless_ngx_default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '8000:8000/tcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
