---
# yamllint disable rule:line-length
# Confirm:
# * paperless.conf set.
# * paperless ngx services are active and running.
# * gunicorn overrides are set correctly.
# * ImageMaick has PDF processing enabled.
# * install directory locations are removed.
# * sqlite database exists in data directory.
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        github_testing_enable: true
        github_testing_versions:
          - 'v2.14.7'
          - '0.30'
          - 'gs10050'
        github_testing_archives:
          - '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/paperless-ngx-v2.14.7.tar.xz'
          - '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/jbig2enc-0.30.tar.gz'
          - '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/ghostscript-10.05.0.tar.xz'
        paperless_ngx_service_nltk_data: []
        paperless_ngx_config_dbengine: 'sqlite'
        paperless_ngx_config_secret_key: 'test'
platforms:
  - name: 'paperless_ngx-debian-12-default'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
