---
- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare cache'

    - name: 'Default | prepare | check paperless ngx v2.16.2'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache paperless ngx v2.16.2'
        test_dest: 'paperless-ngx-v2.16.2.tar.xz'
        test_url: '{{
            "https://github.com/paperless-ngx/paperless-ngx/releases/" ~
            "download/v2.16.2/" ~
            "paperless-ngx-v2.16.2.tar.xz"
          }}'
        test_mode: '0640'

    - name: 'Default | prepare | check JBIG2enc 0.30'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache JBIG2enc 0.30'
        test_dest: '0.30.tar.gz'
        test_url:
          'https://github.com/agl/jbig2enc/archive/refs/tags/0.30.tar.gz'
        test_mode: '0640'

    - name: 'Default | prepare | check Ghostscript 10.05.0'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache Ghostscript 10.05.0'
        test_dest: 'ghostpdl-10.05.0.tar.xz'
        test_url: '{{
            "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/" ~
            "download/gs10050/" ~
            "ghostpdl-10.05.0.tar.xz"
          }}'
        test_mode: '0640'
