---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare cache'

    - name: '{{
          "Prepare | cache Paperless-NGX " ~ paperless_ngx___app._version
        }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: '{{
            "Prepare | cache Paperless-NGX " ~ paperless_ngx___app._version
          }}'
        test_dest: '{{ paperless_ngx___app._package }}'
        test_url: '{{ paperless_ngx___app._url }}'
        test_mode: '0640'

    - name: '{{ "Prepare | cache JBIG2enc " ~ paperless_ngx___jb2e._version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{ "Prepare | cache JBIG2enc " ~ paperless_ngx___jb2e._version }}'
        test_dest: '{{ paperless_ngx___jb2e._package }}'
        test_url: '{{ paperless_ngx___jb2e._url }}'
        test_mode: '0640'

    - name: '{{ "Prepare | cache Ghostscript " ~ paperless_ngx___gs._version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{ "Prepare | cache Ghostscript " ~ paperless_ngx___gs._version }}'
        test_dest: '{{ paperless_ngx___gs._package }}'
        test_url: '{{ paperless_ngx___gs._url }}'
        test_mode: '0640'
