---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare cache'

    - name: 'Prepare | check paperless ngx v2.19.1'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache paperless ngx v2.19.1'
        test_dest: 'paperless-ngx-v2.19.1.tar.xz'
        test_url: '{{
            "https://github.com/paperless-ngx/paperless-ngx/releases/" ~
            "download/v2.19.1/" ~
            "paperless-ngx-v2.19.1.tar.xz"
          }}'
        test_mode: '0640'

    - name: 'Prepare | check JBIG2enc 0.30'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache JBIG2enc 0.30'
        test_dest: '0.30.tar.gz'
        test_url:
          'https://github.com/agl/jbig2enc/archive/refs/tags/0.30.tar.gz'
        test_mode: '0640'

    - name: 'Prepare | check Ghostscript 10.06.0'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache Ghostscript 10.06.0'
        test_dest: 'ghostpdl-10.06.0.tar.xz'
        test_url: '{{
            "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/" ~
            "download/gs10060/" ~
            "ghostpdl-10.06.0.tar.xz"
          }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'paperless_ngx-debian-13-user_data'
  gather_facts: false
  tasks:
    - name: 'Prepare | simulate user media restriction'
      ansible.builtin.file:
        path: '/data'
        owner: 950
        group: 950
        mode: '0755'
        state: 'directory'
