---
# yamllint disable rule:line-length

- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | paperless.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | paperless.conf'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/paperless.conf"
          }}'
        test_file: '/opt/paperless/paperless/paperless.conf'
        test_owner: 'paperless'
        test_group: 'paperless'
        test_mode: '0640'

    - name: 'Default | verify | /opt/paperless/paperless/data'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /opt/paperless/paperless/data'
        test_file: '/opt/paperless/paperless/data'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Default | verify | /data/data/db.sqlite3'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /data/data/db.sqlite3'
        test_file: '/data/data/db.sqlite3'
        test_owner: 'paperless'
        test_group: 'paperless'
        test_mode: '0644'  # Should this be 0644
        # TODO(role): it seems like all data is getting blasted with 0750 perms, instead of file and folder perms. (0640, 0750)
        test_state: 'file'

    - name: 'Default | verify | /etc/ImageMagick-6/policy.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | /etc/ImageMagick-6/policy.xml'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/policy.xml"
          }}'
        test_file: '/etc/ImageMagick-6/policy.xml'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    - name: 'Default | verify | /usr/local/bin/jbig2'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /usr/local/bin/jbig2'
        test_file: '/usr/local/bin/jbig2'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'

    - name: 'Default | verify | /usr/local/bin/gs'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /usr/local/bin/gs'
        test_file: '/usr/local/bin/gs'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
