---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:

    - name: 'Converge | assert deprecated variables are detected'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | assert deprecated variables are detected'
        test_role: 'r_pufky.srv.paperless_ngx'
        test_fail_message:
          'paperless_ngx_cfg_trash_dir did not trigger assertion.'
        paperless_ngx_cfg_trash_dir: '/tmp'
