---
###############################################################################
# Binaries
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#binaries

# Convert binary location. Default: '/usr/bin/convert'.
paperless_ngx_cfg_convert_binary: '/usr/bin/convert'

# GS binary location. Default: '/usr/bin/gs'.
paperless_ngx_cfg_gs_binary: '/usr/local/bin/gs'
