---
###############################################################################
# Binaries
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#binaries

# Convert binary location. Default: '/usr/bin/convert'.
paperless_ngx_config_convert_binary: '/usr/bin/convert'

# GS binary location.
#
# Security: CVE-2023-43115
#   CVE:
#   * https://nvd.nist.gov/vuln/detail/cve-2023-43115
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27835
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27832
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27831
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27836
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27830
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27833
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27837
#   * https://nvd.nist.gov/vuln/detail/cve-2025-27834
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46951
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46952
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46953
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46954
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46955
#   * https://nvd.nist.gov/vuln/detail/cve-2024-46956
#   * https://nvd.nist.gov/vuln/detail/cve-2024-33869
#   * https://nvd.nist.gov/vuln/detail/cve-2023-52722
#   * https://nvd.nist.gov/vuln/detail/cve-2024-33870
#   * https://nvd.nist.gov/vuln/detail/cve-2024-33871
#   * https://nvd.nist.gov/vuln/detail/cve-2024-29510
#  Decision: do not use package - multiple vulnerabilities with PDF corruption
#      for existing files, bookworm package (and backport) affected.
#  Mitigation: use source release. Default gs binary to custom binary location
#      instead of /usr/bin/gs.
#  Reference:
#  * https://github.com/tteck/Proxmox/discussions/3265
#  * https://github.com/ArtifexSoftware/ghostpdl-downloads/releases
#
# Default: '/usr/bin/gs'.
paperless_ngx_config_gs_binary: '/usr/local/bin/gs'
