---
###############################################################################
# Database (Required)
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#database

# Database backend.
#
# Values:
#   postgresql: Postgres. HIGHLY recommended (default).
#      mariadb: MariaDB. MySQL-based databases have caveats. See reference.
#       sqlite: Sqlite3. Not recommended.
#
# Default: 'postgresql'.
#
# Reference:
# * https://docs.paperless-ngx.com/advanced_usage/#mysql-caveats
paperless_ngx_cfg_dbengine: 'postgresql'

# Database host (ignored for sqlite). Default: 'localhost'.
paperless_ngx_cfg_dbhost: 'localhost'

# Database port (ignored for sqlite). Default: 5432.
paperless_ngx_cfg_dbport: 5432

# Database name (ignored for sqlite). Default: 'paperless'.
paperless_ngx_cfg_dbname: 'paperless'

# Database user (ignored for sqlite). Default: 'paperless'.
paperless_ngx_cfg_dbuser: 'paperless'

# Database pass (ignored for sqlite). Default: 'paperless'.
paperless_ngx_cfg_dbpass: 'paperless'

# Database SSL mode.
#
# SSL mode to use when connecting to PostgreSQL or MariaDB; ignored for sqlite.
#
# Special Case:
#   postgresql: prefer (default).
#      mariadb: PREFERRED.
#
# Default: 'prefer' (postgresql).
#
# Reference:
# * https://www.postgresql.org/docs/current/libpq-ssl.html
# * https://dev.mysql.com/doc/refman/8.0/en/connection-options.html
paperless_ngx_cfg_dbsslmode: 'prefer'

# Database SSL root certificate path.
#
# Default: '' (default).
#
# Reference:
# * https://www.postgresql.org/docs/current/libpq-ssl.html
# * https://dev.mysql.com/doc/refman/8.0/en/connection-options.html
paperless_ngx_cfg_dbsslrootcert: ''

# Database SSL client certificate path.
#
# Default: '' (default).
#
# Reference:
# * https://www.postgresql.org/docs/current/libpq-ssl.html
# * https://dev.mysql.com/doc/refman/8.0/en/connection-options.html
paperless_ngx_cfg_dbsslcert: ''

# Database SSL client key path.
#
# Default: '' (default).
#
# Reference:
# * https://www.postgresql.org/docs/current/libpq-ssl.html
# * https://dev.mysql.com/doc/refman/8.0/en/connection-options.html
paperless_ngx_cfg_dbsslkey: ''

# Database timeout in seconds.
#
# Amount of time for a database connection to wait for the database to unlock.
# Mostly applicable for sqlite based installation. Consider changing to
# postgresql if you are having concurrency problems with sqlite.
#
# Special Case:
#   * paperless_ngx_cfg_dbengine=sqlite - How long to wait if the database is
#     locked.
#   * paperless_ngx_cfg_dbengine!=sqlite - Connection timeout.
#
# Values:
#   -1: Use Django built-in defaults (default).
#
# Default: -1 (default).
paperless_ngx_cfg_db_timeout: -1
