---
###############################################################################
# Debugging
###############################################################################

# Enable development debugging? Default: False.
paperless_ngx_cfg_debug: false
