---
###############################################################################
# Debugging
###############################################################################

# Enable development debugging? Default: False.
paperless_ngx_config_debug: false
