---
###############################################################################
# Document Consumption
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#consume_config

# Delete detected duplicate documents? Default: False.
paperless_ngx_cfg_consumer_delete_duplicates: false

# Enable recursive watch of paperless_ngx_cfg_consumption_dir?
#
# Detects file changes for processing.
#
# Default: False.
paperless_ngx_cfg_consumer_recursive: false

# Autotag documents based on paperless_ngx_cfg_consumption_dir?
#
# Requires paperless_ngx_cfg_consumer_recursive=true.
#
# Subdirectories will be converted to tags (<CONSUMPTION_DIR>/foo/bar/file.pdf
# will add tags 'foo' and 'bar' to consumed file). Tags will be created if
# needed, folders will not be deleted.
#
# This is useful for sorting documents with certain tags such as car or todo
# prior to consumption.
#
# Default: False.
paperless_ngx_cfg_consumer_subdirs_as_tags: false

# Files to ignore in paperless_ngx_cfg_consumption_dir.
#
# Default:
#   - '.DS_Store/*'
#   - '.DS_STORE/*'
#   - '._*'
#   - '.stfolder/*'
#   - '.stversions/*'
#   - '.localized/*'
#   - 'desktop.ini'
#   - '@eaDir/*'
#   - 'Thumbs.db'
paperless_ngx_cfg_consumer_ignore_patterns:
  - '.DS_Store/*'
  - '.DS_STORE/*'
  - '._*'
  - '.stfolder/*'
  - '.stversions/*'
  - '.localized/*'
  - 'desktop.ini'
  - '@eaDir/*'
  - 'Thumbs.db'

# Set the barcode scanner used for barcode functionality.
#
# Switch libraries if there are problems with Barcodes/QR-Codes are not
# detected (especially with bad scan quality and/or small codes). Dependencies
# will automatically be installed.
#
# Values:
#   PYZBAR: Use ZBAR libraries.
#    ZXING: Use ZXing libraries.
#
# Default: 'ZXING'.
paperless_ngx_cfg_consumer_barcode_scanner: 'ZXING'

# Pre process document with user defined script.
#
# After some initial validation, Paperless can trigger an arbitrary script
# before beginning consumption. This script will be provided data for it to
# work with via the environment.
#
# Default: '' (disabled).
#
# Reference:
# * https://docs.paperless-ngx.com/advanced_usage/#pre-consume-script
paperless_ngx_cfg_pre_consume_script: ''

# Post process document with user defined script.
#
# After a document is consumed, Paperless can trigger an arbitrary script if
# you like. This script will be provided data for it to work with via the
# environment.
#
# Default: '' (disabled).
#
# Reference:
# * https://docs.paperless-ngx.com/advanced_usage/#pre-consume-script
paperless_ngx_cfg_post_consume_script: ''

# Use specified format for automatic document date detection.
#
# Paperless will check the document text for document date information. The
# filename is checked first, then the document itself.
#
# A date in a filename must have some separators (., ,, -, /, etc) for it to be
# parsed.
#
# Values:
#   '': Disables.
#
# Default: 'YMD'.
#
# Reference:
# * https://dateparser.readthedocs.io/en/latest/settings.html#date-order
paperless_ngx_cfg_filename_date_order: 'YMD'

# Search document for alternative created date suggestions.
#
# Paperless searches an entire document for dates. The first date found will be
# used as the initial value for the created date. When this variable is greater
# than 0 (or left to its default value), paperless will also suggest other
# dates found in the document, up to a maximum of this setting. Note that
# duplicates will be removed, which can result in fewer dates displayed in the
# frontend than this setting value.
#
# The task to find all dates can be time-consuming and increases with a higher
# (maximum) number of suggested dates and slower hardware.
#
# Values:
#   #: Number of dates to find.
#   0: Disables.
#
# Default: 3.
paperless_ngx_cfg_number_of_suggested_dates: 3

# Font to use for plain text file thumbnail generation.
#
# Does not apply to already generated images.
#
# Paperless creates thumbnails for plain text files by rendering the content of
# the file on an image and uses a predefined font for that. This font can be
# changed here.
#
# Default: '/usr/share/fonts/liberation/LiberationSerif-Regular.ttf'.
paperless_ngx_cfg_thumbnail_font_name:
  '/usr/share/fonts/liberation/LiberationSerif-Regular.ttf'

# List of dates that should be ignored during creation date detection.
#
# Useful for special dates (like date of birth) that appear in documents
# regularly but are very unlikely to be the documents creation date.
#
# Date parsed using format in paperless_ngx_cfg_date_order.
#
# Default: [] (consider all dates).
#
# Reference:
# * https://dateparser.readthedocs.io/en/latest/#popular-formats
paperless_ngx_cfg_ignore_dates: []

# Date format expected in documents.
#
# Paperless will try to determine the document creation date from its contents.
# Specify the date format Paperless should expect to see within your documents.
#
# This option defaults to DMY which translates to day first, month second, and
# year last order. Characters D, M, or Y can be shuffled to meet the required
# order.
#
# Special Case:
#   [DMY][DMY][DMY]: Any combination of D (day), M (month), Y (year).
#
# Default: 'DMY'.
paperless_ngx_cfg_date_order: 'DMY'

# Enable GPG decryptor for encrypted emails?
#
# GPG package will automatically be installed.
#
# Default: False.
#
# Reference:
# * https://docs.paperless-ngx.com/advanced_usage/#gpg-decryptor
paperless_ngx_cfg_enable_gpg_decryptor: false
