---
###############################################################################
# Email Parsing
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#email-parsing

# Default layout for emails consumed as documents.
#
# Special Case:
#   * Mail rules can specify this setting, thus this fallback is used for
#     default selection and for .eml files consumed by other means.
#
# Values:
#   1: Text then HTML.
#   2: HTML then text (default).
#   3: HTML only.
#   4: Text only.
#
# Default: 2 (HTML than text).
paperless_ngx_cfg_email_parse_default_layout: 2
