---
###############################################################################
# Email Sending
###############################################################################
# All of these options come from their similarly-named Django settings.
# Setting an SMTP server for the backend will allow you to reset your password.
#
# Reference:
# * https://docs.paperless-ngx.com/configuration/#email-sending

# Email server host. Default: 'localhost'.
paperless_ngx_cfg_email_host: 'localhost'

# Email server port. Default: 25.
paperless_ngx_cfg_email_port: 25

# Email server user: Default: ''.
paperless_ngx_cfg_email_host_user: ''

# Set 'from' email field.
#
# Defaults to paperless_ngx_cfg_email_host_user if not set.
#
# Default: '' (paperless_ngx_cfg_email_host_user).
paperless_ngx_cfg_email_from: ''

# Email password. Default: ''.
paperless_ngx_cfg_email_host_password: ''

# Enable email TLS? Default: False.
paperless_ngx_cfg_email_use_tls: false

# Enable email SSL? Default: False.
paperless_ngx_cfg_email_use_ssl: false
