---
###############################################################################
# Frontend Settings
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#frontend-settings

# Set default application name. Default: 'Paperless-ngx'.
paperless_ngx_cfg_app_title: 'Paperless-ngx'

# Path to a custom logo image file in the /media/logo directory.
#
# Special Case:
#   *: Must include 'logo' (e.g. /logo/Atari_logo.svg).
#
# Default: '' (disabled).
paperless_ngx_cfg_app_logo: ''
