---
###############################################################################
# Incoming Mail
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#incoming_mail

# Base URL for OAuth callback.
#
# Used to construct full URL for OAuth callback. This should be the URL that
# the Paperless instance is accessible at. To enable OAuth this or
# paperless_ngx_config_paperless_url must be set. This setting only applies to
# OAuth Email setup (not to SSO setup).
#
# Default: '' (use paperless_ngx_config_paperless_url).
paperless_ngx_config_oauth_callback_base_url: ''

# Gmail OAuth client ID.
#
# Required for Gmail OAuth Email setup.
#
# Default: ''.
#
# Reference:
# * https://docs.paperless-ngx.com/usage/#oauth-email-setup
paperless_ngx_config_gmail_oauth_client_id: ''

# Gmail OAuth client secret.
#
# Required for Gmail OAuth Email setup.
#
# Default: ''.
#
# Reference:
# * https://docs.paperless-ngx.com/usage/#oauth-email-setup
paperless_ngx_config_gmail_oauth_client_secret: ''

# OAuth client ID for Outlook.
#
# Required for Outlook OAuth Email setup
#
# Default: ''.
#
# Reference:
# * https://docs.paperless-ngx.com/usage/#oauth-email-setup.
paperless_ngx_config_outlook_oauth_client_id: ''

# OAuth client secret for Outlook.
#
# Required for Outlook OAuth Email setup
#
# Default: ''.
#
# Reference:
# * https://docs.paperless-ngx.com/usage/#oauth-email-setup.
paperless_ngx_config_outlook_oauth_client_secret: ''

# Set GNUPG_HOME path to use with GPG decryptor for encrypted emails.
#
# If not set, default GNUPG_HOME path.
#
# Default: '.'.
#
# Reference:
# * https://docs.paperless-ngx.com/advanced_usage/#gpg-decryptor
paperless_ngx_config_email_gnupg_home: '.'
