---
###############################################################################
# Inotify
###############################################################################

# Wait for additional inotify events to consider file ready (seconds).
#
# Once a file is ready it will be consumed. Certain scanners or network setups
# may generate multiple events for a single file, leading to multiple consumers
# working on the same file. Configure this to prevent that.
#
# Default: 0.5.
paperless_ngx_config_consumer_inotify_delay: 0.5
