---
###############################################################################
# Logging
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#logging

# Max log size before rotation (MiB). Default: 1.
paperless_ngx_config_logrotate_max_size: 1

# Max number of rotated logs to keep. Default: 20.
paperless_ngx_config_logrotate_max_backups: 20
