---
# yamllint disable rule:line-length
###############################################################################
# OCR Settings
###############################################################################
# Paperless uses OCRmyPDF for performing OCR on documents and images. Sensible
# defaults are used for most settings. Automatically installed if languages are
# configured.
#
# Reference:
# * https://docs.paperless-ngx.com/configuration/#ocr

# List of languages used for OCR processing.
#
# Multiple languages will be attempted in defined order.
#
# Special Case:
#   *: Specifying ANY language will install OCRmyPDF with required
#      dependencies.
#
# Values:
#   {LANG}: 3-letter language code (see reference). Must use
#           lower_with_under. Multiple languages specified will use the best
#           match.
#
# Default:
#   - 'eng'
#
# Reference:
# * https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html
paperless_ngx_config_ocr_language:
  - 'eng'

# How to perform OCR document scanning.
#
# Values:
#             skip: Skip all pages and perform OCR only on pages where no text
#                   present. This is the safest option.
#   skip_noarchive: In addition to 'skip', paperless won't create an archived
#                   version of your documents when it finds any text in them.
#                   This is useful if you don't want to have two almost
#                   identical versions of your digital documents in the media
#                   folder. This is the fastest option.
#             redo: Paperless will OCR all pages of your documents and attempt
#                   to replace any existing text layers with new text. This
#                   will be useful for documents from scanners that already
#                   performed OCR with insufficient results. It will also
#                   perform OCR on purely digital documents. This option may
#                   fail on some documents that have features that cannot be
#                   removed, such as forms. In this case, the text from the
#                   document is used instead.
#            force: Paperless rasterizes your documents, converting any text
#                   into images and puts the OCRed text on top. This works for
#                   all documents, however, the resulting document may be
#                   significantly larger and text won't appear as sharp when
#                   zoomed in.
#
# Default: 'skip'.
#
# Reference:
# * https://ocrmypdf.readthedocs.io/en/latest/advanced.html#when-ocr-is-skipped
paperless_ngx_config_ocr_mode: 'skip'

# Skip creating an archive version of scanned documents.
#
# Useful if you don't want to have two almost-identical versions of your
# documents in the media folder.
#
# Values:
#       never: Never skip creating an archived version.
#   with_text: Skip creating an archived version for documents that already
#              have embedded text.
#      always: Always skip creating an archived version.
#
# Default: 'never'.
paperless_ngx_config_ocr_skip_archive_file: 'never'

# Use unpaper to clean document before sending to tesseract.
#
# Uses more resources but generally results in better OCR results.
#
# Special Case:
#   clean-final: Incompatible with paperless_ngx_config_ocr_mode=redo. When
#                both clean-final and redo are configured, clean is used.
#
# Values:
#         clean: Apply unpaper (default).
#   clean-final: Apply unpaper, and use the cleaned images to build the output
#                file instead of the original images.
#          none: Do not apply unpaper.
#
# Default: 'clean'.
paperless_ngx_config_ocr_clean: 'clean'

# Deskew images?
#
# Correct skewing (slight rotation of input images mainly due to improper
# scanning).
#
# Special Case:
#   True: Incompatible with paperless_ngx_config_ocr_mode=redo. Disabled
#         automatically if both are set.
#
# Default: True.
paperless_ngx_config_ocr_deskew: true

# Rotate pages to correct orientation based tesseract analysis?
#
# Tells paperless to correct page rotation (90°, 180° and 270° rotation). If
# you notice that paperless is not rotating incorrectly rotated pages (or vice
# versa), try adjusting paperless_ngx_config_ocr_rotate_pages_threshold up or
# down.
#
# Default: True.
paperless_ngx_config_ocr_rotate_pages: true

# Threshold for automatic page rotation.
#
# Decision: use int - documentation refers to use as an int, though example
#     config uses a float.
#
# Values:
#    ~2: Aggressive (likely incorrect results).
#   ~15: Conservative.
#
# Default: 12.
paperless_ngx_config_ocr_rotate_pages_threshold: 12

# Type of documents that OCR should produce.
#
# The original is always kept.
#
# Values:
#        pdf: Modify PDF document as little as possible.
#       pdfa: Convert PDF documents into PDF/A-2b documents, which is a subset
#             of the entire PDF specification and meant for storing documents
#             long term.
#   pdfa-{#}: Exact version of PDF/A to use.
#
# Default: 'pdfa'.
paperless_ngx_config_ocr_output_type: 'pdfa'

# Number of pages to process with OCR.
#
# Documents with less than the specified amount of pages get OCR'ed completely.
#
# Special Case:
#   *: When paperless_ngx_config_ocr_mode=redo|force text found on excluded
#      pages will be copied verbatim.
#
# Values:
#   0: Disabled OCR page limit (default).
#   #: Process OCR to page #.
#
# Default: 0 (disabled).
paperless_ngx_config_ocr_pages: 0

# DPI of scanned images.
#
# Most images from scanners will have DPI information embedded and paperless
# will detect and use that information. In case this fails, it uses this value
# as a fallback.
#
# Values:
#   0: Calculate image DPI so produced PDF documents are A4 sized.
#   #: Set to printer image scan DPI.
#
# Default: 600.
paperless_ngx_config_ocr_image_dpi: 600

# Max OCR image pixel limit.
#
# Does not prevent the document from being consumed, but could result in
# missing text content. Increasing this limit could cause Paperless to consume
# additional resources when consuming a file. Be sure you have sufficient
# system resources.
#
# Limit is intended to prevent malicious files from consuming system resources
# and causing crashes and other errors. Only change this value if you are
# certain your documents are not malicious and you need the text which was not
# OCR'ed.
#
# Special Case:
#     #: Raise warning when OCRing images which are over this limit.
#   2*#: Refuse to OCR images which are more than twice this limit (may result
#        in dropping images).
#     0: Disables limit.
#
# Default: 89478485 (~250MB 24bit/3bpp image).
#
# Reference:
# * https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.MAX_IMAGE_PIXELS
paperless_ngx_config_ocr_max_image_pixels: 89478485

# Ghostscript color conversion strategy when creating the archive file.
#
# Requires paperless_ngx_config_ocr_output_type=pdfa.
#
# Utilizing some of the options may result in errors when creating archive
# files from PDFs.
#
# Values:
#                        CMYK: Use CMYK (print).
#                        Gray: Use Grayscale.
#         LeaveColorUnchanged: Leave colors unchanged (if colorspace allows).
#                         RGB: Use RGB (default).
#   UseDeviceIndependentColor: Use device independent color.
#
# Default: 'RGB'.
#
# Reference:
# * https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#color-conversion-and-management
paperless_ngx_config_ocr_color_conversion_strategy: 'RGB'

# Dict containing additional OCRmyPDF options.
#
# Automatically converted to JSON.
#
# Use this parameter to specify any additional arguments to OCRmyPDF. Specify
# in a format that can be passed to the OCRmyPDF API.
#
# There are many options that are incompatible with each other, so specifying
# invalid options may prevent paperless from consuming any documents.
#
# Special Case:
#    *: Command line options use lower_with_under.
#    *: YAML will automatically be converted to JSON object.
#   "": Use double quotes for correct escape character interpretation for JSON.
#
# Default:
#   optimize: 1  # Enable lossless optimizations.
#   jbig2_lossy: false  # Disable lossy compression.
#
# Reference:
# * https://ocrmypdf.readthedocs.io/en/latest/api.html#reference
# * https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#pdf-optimization
paperless_ngx_config_ocr_user_args:
  optimize: 1
  jbig2_lossy: false
