---
# yamllint disable rule:line-length
###############################################################################
# Paths and Folders
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#paths-and-folders

# Location of user document submissions.
#
# This is where your documents should go to be consumed (processed).
#
# Default: '/data/consume'.
paperless_ngx_config_consumption_dir: '/data/consume'

# Location of configuration data.
#
# This is where paperless stores all its data (search index, SQLite database,
# classification model, etc).
#
# Default: '/data/data'.
paperless_ngx_config_data_dir: '/data/data'

# Location of trashed items.
#
# When documents are deleted (e.g. after emptying the trash) the original files
# will be moved here instead of being removed from the filesystem. Only the
# original version is kept. Previously pngx_trash_dir.
#
# Special Case:
#   '': Permanently delete files instead of moving to trash (default).
#
# Default: ''.
paperless_ngx_config_empty_trash_dir: ''

# Location of stored user data (documents, thumbnails, etc).
#
# May be the same as paperless_ngx_config_data_dir.
#
# Default: '/data/media'.
paperless_ngx_config_media_root: '/data/media'

# Location of static serving directory.
#
# This is where all static files created using "collectstatic" manager command
# are stored. Unless you're doing something fancy, there is no need to override
# this. If this is changed, you may need to run "collectstatic" again.
#
# If you don't know why you should change this, don't.
#
# Default: '../static'.
paperless_ngx_config_staticdir: '../static'

# Ingested media file naming conventions.
#
# If this is changed after documents are loaded run 'document_renamer' to mass
# update files. You many need to temporarily enable the
# paperless_ngx_user user shell to login and run the command.
#
#   su - paperless_ngx_user
#   . /var/venv/paperless/bin/activate
#   cd /var/lib/paperless-ngx-X.X.X/src
#   python3 manage.py document_renamer
#
# Special Case:
#   *: Use '!unsafe' for double curly bracket replacements.
#
# Values:
#   '': Disabled renaming (default).
#
# Default: !unsafe '' (disabled).
#
# Reference:
# * https://docs.paperless-ngx.com/advanced_usage/#file-name-handling
# * https://docs.paperless-ngx.com/advanced_usage/#advanced-file-name-handling
# * https://docs.paperless-ngx.com/administration/#management-utilities
# * https://docs.paperless-ngx.com/administration/#renamer
paperless_ngx_config_filename_format: !unsafe ''

# Omit filename/directory placeholders that resolve to 'none'.
#
# Applied to paperless_ngx_config_filename_format transformations.
#
# Default: False (disabled).
paperless_ngx_config_filename_format_remove_none: false

# Log location. Default: '{{ paperless_ngx_config_data_dir }}/log'.
paperless_ngx_config_logging_dir: '{{ paperless_ngx_config_data_dir }}/log'

# Location for NLTK data processing if used.
#
# Old installation no longer use the 'NLTK' directory and can safely be
# removed.
#
# Defaults: '/usr/share/nltk_data'.
paperless_ngx_config_nltk_dir: '/usr/share/nltk_data'

# Where paperless classification models are stored.
#
# Default: '{{ paperless_ngx_config_data_dir }}/classification_model.pickle'.
paperless_ngx_config_model_file: '{{ paperless_ngx_config_data_dir }}/classification_model.pickle'
