---
###############################################################################
# Redis (Required)
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#redis-broker

# Redis server location.
#
# Processes scheduled tasks such as email fetching, index optimization and for
# training the automatic document matcher.
#
# Special Case:
#   {URI}: {PROTO}://{USER}:{PASS}@{HOST}:{PORT}/{DB_INDEX}. Connection string
#          may contain the minimum number of fields to connect. For redis with
#          requirepass=true, use 'redis://:{PASS}...'.
#
# Default: 'redis://localhost:6379'.
paperless_ngx_cfg_redis: 'redis://localhost:6379'

# Redis prefix.
#
# Prefix to be used in Redis for keys and channels. Useful for sharing one
# Redis server among multiple Paperless instances.
#
# Default: '' (no prefix).
paperless_ngx_cfg_redis_prefix: ''
