---
###############################################################################
# Workflow Webhooks
###############################################################################
# Reference:
# * https://docs.paperless-ngx.com/configuration/#workflow-webhooks

# List of URL schemes permitted to access webhook URLs.
#
# Default: ['http', 'https'] (default).
paperless_ngx_cfg_webhooks_allowed_schemes:
  - 'http'
  - 'https'

# List of allowed ports for webhooks.
#
# Values:
#   []: Allow all ports (default).
#
# Default: [] (all ports).
paperless_ngx_cfg_webhooks_allowed_ports: []

# Allow internal webhook requests (e.g. localhost)? Default: True.
paperless_srv_webhooks_allow_internal_requests: true
